#!/bin/bash

# try including handy bash library functions 
. lib/testtoolkit.bashlib || . ../lib/testtoolkit.bashlib || . ../../lib/testtoolkit.bashlib 


echo "[x] shared vars are: $BASEURL, $BASEDIR, $ERNAME, PASSWORD, $COOKIE, $COOKIEJAR, $LOGFILE, $EMAIL, $VERBOSE"

printf "\n\n(this test is out of order for now)\n\n"
exit 0

# test if urls are accessible
_test-url "$BASEURL"                                                       "html"
_test-url "$BASEURL/s/js/multiple/lib_mootools_mootools-1.3.2.js"          "js"

#
# possible data integration tests
#

_test-url-url-in-xml-tag       "$baseurl/data/live.xml"                    "<video> <thumb>"
_test-url-url-in-xml-attribute "$baseurl/data/wallpaper.xml"               "<image>" "url"
# echo "[x] running php code"
# _run-php "print_r($_GET);"

#
# check all links on channel websites (requires 'linklint' installed)
#
# _test-links "$baseurl"
